/*
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package org.xtext.example.mydsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ApiStandaloneSetup extends ApiStandaloneSetupGenerated {

	def static void doSetup() {
		new ApiStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
