/*
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package org.xtext.example.mydsl.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.example.mydsl.ApiRuntimeModule
import org.xtext.example.mydsl.ApiStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class ApiIdeSetup extends ApiStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new ApiRuntimeModule, new ApiIdeModule))
	}
	
}
